### ISSUE TITLE
Balance problem on mac?

### ISSUE THREAD

**Issue by vlad-cotfas** [InerziaSoft/ISSoundAdditions#3] opened 2021-10-17 00:46 UTC
Is there any problem with the balance on mac catalina when up/down the volume the balance is screwed to left speaker when calling:

+ (void)setSystemVolume:(float)theVolume

**Comment by vlad-cotfas** [comment] 2021-10-17 00:57
When connected to headsets and doing up/down for volume the balance is switched to LEFT:

<img width="669" alt="image" src="https://user-images.githubusercontent.com/3340367/137605963-fc8de14d-e886-4feb-b8d3-9f4a9ef0ba4c.png">

I am not sure how this happens? Does anyone know? 

Thank you

**Comment by vlad-cotfas** [comment] 2021-10-17 00:58
AH.. I see this happens when the Boom Audio it is active..

**Comment by vlad-cotfas** [comment] 2021-10-17 01:38
This didn`t happend before they did update their boom2 driver app on mac catalina device..

**Comment by MrAsterisco** [comment] 2022-03-06 12:41
Closing as this seems to be caused by a 3rd-party app. @cotfas feel free to reopen if that’s not the case.

**Closed as completed by MrAsterisco** 2022-03-06 12:41 UTC

**Comment by vlad-cotfas** [comment] 2022-03-06 13:28
Yes, I noticed it is caused by 3rd party. But I fixed it with apple-script exec from cli:

```
-- Check if output is muted
set isMuted to (output muted of (get volume settings))

-- Use the "reset volume" side effect to reset the output balance
set volume output volume (output volume of (get volume settings))

-- Restore muted output state
if (isMuted) is true then
	set volume with output muted
end if
```

**Comment by MrAsterisco** [comment] 2022-03-07 08:03
That's interesting. I wonder if it makes sense to include it directly in the library... What do you think?

**Comment by vlad-cotfas** [comment] 2022-03-07 11:34
Hm, only as an option maybe, but as you have actual code (c,obj,swift) I would say that apple-script would be a hack :S

**Comment by MrAsterisco** [comment] 2022-03-08 11:04
Yeah, I agree 😊  Let's see if other people also report this: if that's the case, we can add an option or an additional call that also performs this "reset" (using the native methods, not the AppleScript code, of course).

**Comment by vlad-cotfas** [comment] 2022-03-08 11:12
Hmmmm, If you have the native methods, I would like to have them if possible. I have a private project for Trackpad and sound control. :D

**Comment by MrAsterisco** [comment] 2022-03-08 14:09
Well, you can already use the existing methods in this library and follow the same procedure, right?
